#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo Hello World | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
