#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get install -y nginx
sudo uwf allow 'Full'
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx
