#!/usr/bin/env bash
# Install NGINX and restart the service and redirecto to anoter page
sudo apt-get update
sudo apt-get install nginx -y

sudo sed -i '/server_name.*/a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
