#!/usr/bin/env bash
# Configure a Ubuntu machine when querying Nginx at its root
# and create a personal header response 
	sudo apt-get update
	sudo apt-get install nginx -y
	echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
	sudo sed -i "/server_name _.*/a  \\trewrite ^/redirect_me\/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/la_404.html;" /etc/nginx/sites-available/default
	echo -e "Ceci n'est pas une page\n\n" | sudo tee /var/www/html/la_404.html
	sudo sed -i "/http {/a \\tadd_header X-Served-By '$HOSTNAME';" /etc/nginx/nginx.conf
	sudo service nginx restart
