#!/usr/bin/env bash
# Configure a Ubuntu machine when querying Nginx at its root
# and create a personal header response
#!/usr/bin/env bash
# script to install nginx and configure its landing page

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i '/^\tserver_name.*/a \\n\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/error404.html;' /etc/nginx/sites-available/default
sudo sed -i '/^\tinclude \/etc\/nginx\/sites-enabled\/\*;/a \\n\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
