#!/usr/bin/env bash
# Configure a Ubuntu machine to install haproxy and configure
# HAproxy so that it send traffic to web-01 and web-02

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0\*
sudo  sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.back
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\t server 3942-web-01 34.139.202.181:80 check\n\tserver 3942-web-02 54.234.28.154:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
