#!/usr/bin/env bash
# Bash script that displays I am invincible! when ignores the SIGTERM with trap
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo I hate the kill command; rm /var/run/myscript.pid; sudo pkill $$' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'rm -rf /var/run/myscript.pid; sudo pkill $$' SIGQUIT
done
