#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd in an specific format

buffer="/etc/passwd"
while IFS=":" read -r Username _ User_ID _ _ Home_directory _
do
	echo "$Username:$User_ID:$Home_directory"
done < $buffer
