#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd in an specific format

buffer="/etc/passwd"
while IFS=":" read -r Username Password User_ID Group_ID User_ID_Info Home_directory Command
do
	echo "$Username:$User_ID:$Home_directory"
done < $buffer
