#!/usr/bin/env bash
#Bash script that gives you information about the school file
var="$(file school)"
if [ -a "$var" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi

if [ -s "$var" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ -f "$var" ]
then
	echo "school is a regular file"
fi
